function isPunc = is_punc(character)
    isPunc = ((character >= 33 && character <= 47) ...
        || (character >= 58 && character <= 64) ...
        || (character == 10) || (character == 13) ...
        || character == 8212); % txt file contains non-ascii characters
    % the input may require more accomodation, have not checked
end